services:
  app:
    build:
      context: ../app
      dockerfile: ../02-apache/Dockerfile
    volumes:
      - ../app/:/var/www/html/
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8002:80"
