services:
  app:
    build:
        context: ../
        dockerfile: 04-serverless/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ../app/bootstrap:/app/bootstrap
      - ../app/config:/app/config
      - ../app/public:/app/public
      - ../app/src:/app/src
      - vendor:/app/vendor/
      - nodeModules:/app/node_modules/
    env_file:
      - .env
    command: npm run deploy

volumes:
  vendor:
    driver: local
  nodeModules:
    driver: local
