services:
  app:
    build:
        context: ./
    working_dir: /app
    volumes:
      - ../app/public:/app/public/
      - ../app/src:/app/src/
      - vendor:/app/vendor/
      - nodeModules:/app/node_modules/
    ports:
      - "8004:80"
    env_file:
      - .env
    command: npm run deploy

volumes:
  vendor:
    driver: local
  nodeModules:
    driver: local
