service: app

provider:
    name: aws
    region: sa-east-1

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
    api:
        handler: public/index.php
        description: ''
        runtime: php-84-fpm
        timeout: 28 # segundos (API Gateway tem um timeout padrão de 29 segundos)
        events:
            -   httpApi: '*'

# arquivos estáticos
constructs:
  website:
    type: server-side-website
    assets:
      '/assets/*': public/assets

# ignorando arquivos ao fazer deploy
package:
    patterns:
        - '!node_modules/**'
        - '!.gitignore'
        - '!.env'
        - '!.env.dist'
